-- MySQL Script generated by MySQL Workbench
-- ter 04 out 2022 14:38:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Equipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Equipes` (
  `equipe_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(500) NOT NULL,
  `sigla` VARCHAR(500) NOT NULL,
  `bandeira` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`equipe_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `equipe_id` INT NOT NULL,
  `nome` VARCHAR(500) NOT NULL,
  `email` VARCHAR(500) NOT NULL,
  `foto` VARCHAR(255) NULL,
  `data_nascimento` DATE NOT NULL,
  PRIMARY KEY (`usuario_id`),
  INDEX `fk_Usuarios_Equipes_idx` (`equipe_id` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Equipes`
    FOREIGN KEY (`equipe_id`)
    REFERENCES `mydb`.`Equipes` (`equipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tecnicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tecnicos` (
  `tecnico_id` INT NOT NULL AUTO_INCREMENT,
  `equipe_id` INT NOT NULL,
  `nome` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`tecnico_id`),
  INDEX `fk_Tecnicos_Equipes_idx` (`equipe_id` ASC) VISIBLE,
  CONSTRAINT `fk_Tecnicos_Equipes`
    FOREIGN KEY (`equipe_id`)
    REFERENCES `mydb`.`Equipes` (`equipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Atletas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Atletas` (
  `atleta_id` INT NOT NULL AUTO_INCREMENT,
  `equipe_id` INT NOT NULL,
  `nome` VARCHAR(500) NOT NULL,
  `foto` VARCHAR(500) NOT NULL,
  `nacionalidade` VARCHAR(255) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `peso` DECIMAL(10,2) NOT NULL,
  `numero_camisa` INT NOT NULL,
  `altura` DECIMAL(10,2) NOT NULL,
  `pe_dominante` TINYINT NOT NULL COMMENT '0 - Destro\n1 - Canhoto\n',
  PRIMARY KEY (`atleta_id`),
  INDEX `fk_Atletas_Equipes1_idx` (`equipe_id` ASC) VISIBLE,
  CONSTRAINT `fk_Atletas_Equipes1`
    FOREIGN KEY (`equipe_id`)
    REFERENCES `mydb`.`Equipes` (`equipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Campeonato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Campeonato` (
  `campeonato_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(500) NOT NULL,
  `situacao` TINYINT NOT NULL COMMENT '0 - Lancada\n1 - Iniciada\n2 - Concluida',
  PRIMARY KEY (`campeonato_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fases` (
  `fase_id` INT NOT NULL AUTO_INCREMENT,
  `campeonato_id` INT NOT NULL,
  `nome` VARCHAR(500) NOT NULL,
  `ordem` INT NULL,
  `situacao` TINYINT NOT NULL COMMENT '0 - Lancada\n1 - Iniciada\n2 - Concluida',
  PRIMARY KEY (`fase_id`),
  INDEX `fk_Fases_Campeonato1_idx` (`campeonato_id` ASC) VISIBLE,
  CONSTRAINT `fk_Fases_Campeonato1`
    FOREIGN KEY (`campeonato_id`)
    REFERENCES `mydb`.`Campeonato` (`campeonato_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Grupos` (
  `grupo_id` INT NOT NULL AUTO_INCREMENT,
  `fase_id` INT NOT NULL,
  `nome` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`grupo_id`),
  INDEX `fk_Grupos_Fases1_idx` (`fase_id` ASC) VISIBLE,
  CONSTRAINT `fk_Grupos_Fases1`
    FOREIGN KEY (`fase_id`)
    REFERENCES `mydb`.`Fases` (`fase_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Partidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Partidas` (
  `partida_id` INT NOT NULL AUTO_INCREMENT,
  `grupo_id` INT NOT NULL,
  `equipe_id_mandante` INT NOT NULL,
  `equipe_id_visitante` INT NOT NULL,
  `data` DATETIME NOT NULL,
  `situacao` TINYINT NOT NULL COMMENT '0 - Lancada\n1 - Iniciada\n2 - Concluida',
  PRIMARY KEY (`partida_id`),
  INDEX `fk_Partidas_Grupos1_idx` (`grupo_id` ASC) VISIBLE,
  INDEX `fk_Partidas_Equipes1_idx` (`equipe_id_mandante` ASC) VISIBLE,
  INDEX `fk_Partidas_Equipes2_idx` (`equipe_id_visitante` ASC) VISIBLE,
  CONSTRAINT `fk_Partidas_Grupos1`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `mydb`.`Grupos` (`grupo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partidas_Equipes1`
    FOREIGN KEY (`equipe_id_mandante`)
    REFERENCES `mydb`.`Equipes` (`equipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partidas_Equipes2`
    FOREIGN KEY (`equipe_id_visitante`)
    REFERENCES `mydb`.`Equipes` (`equipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Escalacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Escalacao` (
  `partida_id` INT NOT NULL,
  `atleta_id` INT NOT NULL,
  `situacao` TINYINT NOT NULL COMMENT '0 - Cancelado\n1 - Titular\n2 - Reserva',
  INDEX `fk_Escalacao_Partidas1_idx` (`partida_id` ASC) VISIBLE,
  INDEX `fk_Escalacao_Atletas1_idx` (`atleta_id` ASC) VISIBLE,
  PRIMARY KEY (`partida_id`, `atleta_id`),
  CONSTRAINT `fk_Escalacao_Partidas1`
    FOREIGN KEY (`partida_id`)
    REFERENCES `mydb`.`Partidas` (`partida_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Escalacao_Atletas1`
    FOREIGN KEY (`atleta_id`)
    REFERENCES `mydb`.`Atletas` (`atleta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estatisticas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estatisticas` (
  `estatistica_id` INT NOT NULL AUTO_INCREMENT,
  `partida_id` INT NOT NULL,
  `equipe_id` INT NOT NULL,
  `atleta_id` INT NOT NULL,
  `tipo` TINYINT NOT NULL COMMENT '0 - GOL\n1 - Cartao Amarelo\n2 - Cartao Vermelho\n3 - Impedimento\n4 - Falta',
  `tempo` TINYINT NOT NULL COMMENT '0 - Primeiro Tempo\n1 - Primeiro Tempo\n2 - Segundo Tempo\n3 - Primeiro Tempo Prorragacao\n4 - Segundo Tempo Prorrogacao\n5 - Penaltis',
  `minutos` INT NULL,
  PRIMARY KEY (`estatistica_id`),
  INDEX `fk_Estatisticas_Escalacao1_idx` (`partida_id` ASC, `equipe_id` ASC, `atleta_id` ASC) VISIBLE,
  CONSTRAINT `fk_Estatisticas_Escalacao1`
    FOREIGN KEY (`partida_id` , `atleta_id`)
    REFERENCES `mydb`.`Escalacao` (`partida_id` , `atleta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
